export const routes = {
  BOTTOM_TAB: 'BOTTOM_TAB',
  HOME_SCREEN: 'HOME_SCREEN',
  CART_SCREEN: 'CART_SCREEN',
  PRODUCT_SCREEN: 'PRODUCT_SCREEN',
  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
};
